name: Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker buildx build -f build.Dockerfile --platform linux/arm64 . --tag ghcr.io/milgradesec/coredns:arm64 --push
          docker buildx build -f build.Dockerfile --platform linux/amd64 . --tag ghcr.io/milgradesec/coredns:amd64 --push
          docker manifest create ghcr.io/milgradesec/coredns:v1.8.4 ghcr.io/milgradesec/coredns:arm64 ghcr.io/milgradesec/coredns:amd64
          docker manifest create ghcr.io/milgradesec/coredns:latest ghcr.io/milgradesec/coredns:arm64 ghcr.io/milgradesec/coredns:amd64
          docker manifest push --purge ghcr.io/milgradesec/coredns:v1.8.4
          docker manifest push --purge ghcr.io/milgradesec/coredns:latest
