name: Docker Release

on:
  push:
    branches: [main]
    paths:
      - "build.Dockerfile"
      - "plugin.cfg"
      - ".github/workflows/docker-release.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/coredns
  VERSION: v1.9.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          file: build.Dockerfile
          build-args: VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
